---
abstract: 'Archive Devel::Cover reports'
author:
  - 'Thomas Klausner <domm@cpan.org>'
build_requires:
  File::Copy::Recursive: 0
  File::Temp: 0
  Module::Build: 0.3601
  Path::Class: 0
  Test::File: 0
  Test::More: 0
  Test::Most: 0
  Test::Trap: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300025, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-ArchiveDevelCover
requires:
  DateTime: 0
  File::Copy: 0
  HTML::TableExtract: 0
  Moose: 0
  MooseX::Getopt: 0
  MooseX::Types::Path::Class: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/domm/App-ArchiveDevelCover.git
version: 1.002
